// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCPXGQF3u7c8UyIQa1mO_NC6-b7ebv-cG4',
    appId: '1:763698865387:web:420d2b8c5e3fde4fe9caae',
    messagingSenderId: '763698865387',
    projectId: 'quickbites-73928',
    authDomain: 'quickbites-73928.firebaseapp.com',
    storageBucket: 'quickbites-73928.firebasestorage.app',
    measurementId: 'G-NBN6TL3XH4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBXz6MzWy66uRxEpS8-W7PdBEEvDwpqUcY',
    appId: '1:763698865387:android:617cb7d6d900c9cee9caae',
    messagingSenderId: '763698865387',
    projectId: 'quickbites-73928',
    storageBucket: 'quickbites-73928.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD41Ibgm9kzG4JnXerIh7e5PGV4ljBgqko',
    appId: '1:763698865387:ios:6f5a59ad6308fabce9caae',
    messagingSenderId: '763698865387',
    projectId: 'quickbites-73928',
    storageBucket: 'quickbites-73928.firebasestorage.app',
    iosBundleId: 'com.skillsphere.quickBites',
  );
}
